### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ErickKS** [g-nik1ta/weather-forecast-app#1]
Hello!

I was looking at your project and I have a suggestion for you.
You can select a city by default so that data for that city will already appear when the user loads the page.
Because when we load the page, it seems that your project is not working, the icons do not appear and only the static data appears.

Notes: Try putting the data directly into JavaScript

**Comment by g-nik1ta** [comment]
Hi!
I had such an idea. I fixed a few bugs and everything should work now on page reload.
